# Generated by Django 2.1 on 2018-09-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sort',
            field=models.IntegerField(blank=True, default=0, verbose_name='排序'),
        ),
    ]
