# Generated by Django 2.1 on 2018-09-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='菜单名称')),
                ('permissions', models.ManyToManyField(blank=True, to='rbac.Permission', verbose_name='菜单权限列表')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单列表',
            },
        ),
        migrations.AlterField(
            model_name='group',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='rbac.Permission', verbose_name='用户组权限列表'),
        ),
    ]
